server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;

    add_header Cache-Control "no-store" always;
    add_header Retry-After "120" always;

    location ~* \.(css|svg|woff2?|ttf|otf|eot|png|jpe?g|ico)$ {
        try_files $uri =503;
    }

    location / {
        return 503;
    }

    error_page 503 /index.html;
    location = /index.html { internal; }
}
